name: Renovate CI

on:
  push:
    # Only run this workflow for branches created by Renovate
    branches:
      - 'renovate/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # adjust node version as needed

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
