name: Run Tests

on: [push]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate test matrix
        id: set-matrix
        run: |
          echo "Searching for test files..."
          # Adjust the path if needed:
          testFiles=$(find ./yetanotherfrontend/__test__ -maxdepth 1 -name "*.test.js")
          if [ -z "$testFiles" ]; then
            echo "No test files found."
            echo "matrix={}" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Convert the newline-separated list into a compact JSON array (single line)
          json_array=$(echo "$testFiles" | jq -R -s -c 'split("\n")[:-1]')
          # Build the matrix JSON object in compact form using the -c flag
          matrix_json=$(jq -c -n --argjson files "$json_array" '{ testFile: $files }')
          echo "Matrix JSON: $matrix_json"
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./yetanotherfrontend

      - name: Run test
        run: npm run test:singlefile -- ${{ matrix.testFile }}
        working-directory: ./yetanotherfrontend
