name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./yetanotherfrontend

      - name: Tests summary
        id: tests-summary
        run: npm run test:start | tee temp_output.txt | grep -E 'passing' && tail -n 10 || (grep -E 'failing' && tail -n 10 || cat temp_output.txt) && rm temp_output.txt # it aint that hard lil bro
        working-directory: ./yetanotherfrontend
