name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./yetanotherfrontend

      - name: Tests summary
        id: tests-summary
        run: npm run test:start | grep -E 'passing|failing' | tail -n 10
        working-directory: ./yetanotherfrontend
        continue-on-error: true
      
      - name: Run tests (full debuggable)
        if: failure()
        id: run-tests
        run: npm run test:start
        working-directory: ./yetanotherfrontend
