name: Update Changelog

on:
  push:
    branches:
      - code

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout main branch
      run: git checkout main

    - name: Get commit messages from code branch
      id: get_commits
      run: |
        git checkout code
        COMMITS=$(git log main..code --pretty=format:"- %s")
        echo "::set-output name=commits::$COMMITS"
        echo "Commit messages: $COMMITS"

    - name: Get messages and date and checkout main branch
      run: |
        COMMITS=$(git log --oneline --no-merges $(git rev-parse HEAD^)..HEAD)
        DATE=$(date)
        echo "Commit messages: $COMMITS"
        git checkout main

    - name: Update changelog
      run: |
        sed -i "10a# $(date '+%Y-%m-%d %H:%M:%S')\n\n${COMMITS}\n" ./content/changelog.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./content/changelog.md
        git commit -m "Update changelog with latest commit messages"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger pages workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/isaaclins/YetAnotherDiscordBotnet/actions/workflows/pages.yaml/dispatches \
          -d '{"ref":"main"}'