name: Update Changelog

on:
  push:
    branches:
      - code

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Get latest commit message
      id: get_commit
      run: |
        git fetch
        git checkout code
        # Get the commits by date and format them, then sort them by date
        git log --pretty=format:'%ad %h %s' --date=format:'%Y-%m-%d' | sort | awk '
        {
            date = $1;
            $1 = "";
            commits[date] = commits[date] "\n" $0 "\n";
        }
        END {
            for (date in commits) {
                print "## " date;
                print commits[date];
                print "\n";
            }
        }
        ' > commits.txt

    - name: Change branch and save commit messages
      run: |
        git checkout main
        awk 'NR==11 {print; system("cat commits.txt"); next} 1' content/changelog.md > temp && mv temp content/changelog.md && rm commits.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add content/changelog.md
        git commit -m "Update changelog with latest commit message"
        git push

    - name: Trigger pages workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/isaaclins/YetAnotherDiscordBotnet/actions/workflows/pages.yaml/dispatches \
          -d '{"ref":"main"}'