name: Update Changelog

on:
  push:
    branches:
      - code

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Get latest commit message
      id: get_commit
      run: |
        # Get the commits by date and format them, then sort them by date
        git log --pretty=format:'%ad %h %s' --date=format:'%d-%m-%Y' | sort | awk '
        {
            date = $1;
            $1 = "";
            commits[date] = commits[date] "\n" $0 "\n";
        }
        END {
            for (date in commits) {
                print "## " date;
                print commits[date];
                print "\n";
            }
        }' > ${{ steps.get_commit.outputs.commits }}

    - name: Change branch and save commit messages
      run: |
        git checkout main
        awk 'NR==11 {print; system("cat ${{ steps.get_commit.outputs.commits }}"); next} 1' content/changelog.md > temp && mv temp content/changelog.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add content/changelog.md
        git commit -m "Update changelog with latest commit message"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}