name: Update Changelog

on:
  push:
    branches:
      - code

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set git config NAME & set git config EMAIL
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Switch to main branch
      run: git checkout main
        
    - name: Add commit messages to changelog and cat it
      run: |
        DATE=$(date)
        COMMITS=$(git log --pretty=format:"%h %s%n" @{u})
        sed -i "10a ## $DATE" ./content/changelog.md
        sed -i "11a $COMMITS" ./content/changelog.md
        cat ./content/changelog.md


    - name: Add changelog to git staging
      run: git add ./content/changelog.md

    - name: Commit and push changes
      run: git commit -m "Update changelog with latest commit messages"  

    - name: Push changes to main branch
      run: git push origin main

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger pages workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/isaaclins/YetAnotherDiscordBotnet/actions/workflows/pages.yaml/dispatches \
          -d '{"ref":"main"}'