name: Update Changelog

on:
  push:
    branches:
      - code

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set Git Config
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Switch to main branch
      run: git checkout main

    - name: Pull latest changes
      run: git pull origin main

    - name: Update Changelog
      run: |
        git log --pretty=format:"%ad %h %s" --date=iso | \
        awk '{date=substr($0, 1, 19); hash=$2; $1=$2=$3=""; msg=substr($0, 5); print date, hash, msg}' | \
        sort -r | \
        awk '
        BEGIN { prev_date = "" }
        {
          date = substr($0, 1, 10);
          time = substr($0, 12, 8);
          hash = $11;
          $1=$2=$3=""; msg=substr($0, 4);
          if (prev_date != date) {
            if (NR != 1) { print "" }
            print "## " date " " time;
          }
          prev_date = date;
          print hash, msg;
        }' | \
        sed '11r /dev/stdin' ./content/changelog.md > ./content/changelog.tmp && mv ./content/changelog.tmp ./content/changelog.md

    - name: Add Changelog to Staging
      run: git add ./content/changelog.md

    - name: Commit Changes
      run: |
        git commit -m "Update changelog with latest commit messages" || echo "No changes to commit"

    - name: Push Changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger Pages Workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/isaaclins/YetAnotherDiscordBotnet/actions/workflows/pages.yaml/dispatches \
          -d '{"ref":"main"}'
